require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe UserSessionsController do

  def stub_user_session(stubs={})
    @stub_user_session ||= stub(UserSession, stubs)
  end

  describe "GET new" do
    it "assigns a new user_session as @user_session" do
      UserSession.stub(:new) { stub_user_session }
      get :new
      assigns(:user_session).should be(stub_user_session)
    end
  end

  describe "POST create" do

    it "tries to create new user_session" do
      UserSession.should_receive(:new).with({ 'these' => 'params' }) {
        stub_user_session(:save => true)
      }
      post :create, :user_session => { 'these' => 'params' }
    end

    context "when user_session saves successfully" do
      it "redirects to :root" do
        UserSession.stub(:new) { stub_user_session(:save => true) }
        post :create, :user_session => {}
        response.should redirect_to(:root)
      end
    end

    context "when user_session fails to save" do
      before :each do
        UserSession.stub(:new) { stub_user_session(:save => false) }
      end

      it "assigns it as @user_session" do
        post :create, :user_session => {}
        assigns(:user_session).should be(stub_user_session)
      end

      it "re-renders the 'new' template" do
        post :create, :user_session => {}
        response.should render_template('new')
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the current user_session" do
      UserSession.stub(:find) { stub_user_session }
      stub_user_session.should_receive(:destroy)
      delete :destroy
    end

    it "redirects to the :users" do
      UserSession.stub(:find) { stub_user_session(:destroy => true) }
      delete :destroy
      response.should redirect_to(:users)
    end
  end

end
